name: CI/CD Pipeline for React App

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define environment for deployment approval
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run unit tests
      - name: Run tests
        run: npm test

      # Build the application
      - name: Build application
        run: npm run build

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      # Compress the build directory into a zip file
      - name: Compress build directory
        run: |
          zip -r build.zip build/

      # Create a GitHub release
      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: Automatic release for commit ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN

      # Upload build artifact to the release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/
          asset_name: build.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN

  deploy:
    runs-on: ubuntu-latest
    needs: release
    environment:
      name: production
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the application
      - name: Build application
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN
          publish_dir: ./build

  notify-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: [build, release, deploy]
    steps:
      # Send email notification on failure
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI/CD Pipeline Failed"
          body: "The CI/CD pipeline for your React app has failed. Please check the logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: dbasoft22@gmail.com
          from: dbasoft22@gmail.com